### ISSUE TITLE
Where to find pre-trained char-RNN text encoder model listed in paper

### ISSUE THREAD

**Issue by vlad3996** [ypxie/HDGan#10]
In your paper you say "p_data denotes a sentence embedding (generated by a pre-trained char-RNN text encoder [34])." 

Can you clarify what model do you use to create coco text embeddings? 

I can not find [here](https://github.com/reedscot/icml2016) appropriate pre-trained model to generate 1024-d coco embeddings.

**Comment by zizhaozhang** [comment]
It is in the readme [Acknowledgement](https://github.com/ypxie/HDGan#acknowlegements)
