### ISSUE TITLE
Questions about preprocessing and evaluation

### ISSUE THREAD

**Issue by dougsouza** [ypxie/HDGan#13]
Hello,

First, congrats, that's a very nice work. I have two simple questions about it:

1. How preprocessing is performed? I couldn't see the script that preprocesses the datastes, only preprocessed datasets for download.
2. How do we choose the number of samples for testing (for inception score, for example) and how this number affects the scores?

Thanks

**Comment by ypxie** [comment]
Hello, thanks for your interest!
1. For fair comparison, we follow the same data preprocessing (mainly some random crops) as Stackgan https://github.com/hanzhanggit/StackGAN
2. Also similar to Stackgan, we sample about 30000 samples to evaluate the Inception score. In general, the more samples we generate, the better the score could reflect the model's performance.
