### ISSUE TITLE
about VS similarity 

### ISSUE THREAD

**Issue by Blue-Clean** [ypxie/HDGan#17]
hello , thanks for your nice works. i have one question, the 30000 generated image  must to be processed the .h5 format? can you tell me how to do it in details? my generated image is at /netG_epoch_600/valid/single/001.*******, and the total directories is 50, total images is 30000.

**Comment by ypxie** [comment]
it should be in the testing function, you can choose to save your generated images.https://github.com/ypxie/HDGan/blob/master/HDGan/HDGan_test.py#L138
