### ISSUE TITLE
论文读后 疑问

### ISSUE THREAD

**Issue by MLjian** [ypxie/HDGan#19]
谢谢你的这篇论文，让我收益良多。只是有二个地方有些疑问，希望作者能给出你的看法：
（1）为什么你不是直接将text_embedding送入网络中直接进行计算，而是对text_embedding进行了两种变化：condEmbedding 和  z。有了这两种变化相当于引入随机噪声，改变了文本数据的分布，感觉不是很合理啊。
（2）实验过程中，你有尝试使用Image-image的L1损失么？
谢谢啦。

**Comment by ypxie** [comment]
Thanks~
1. “引入随机噪声” 是为了生成样本更多样
2. 没有尝试 “Image-image的L1损失” 因为感觉输入不同的情况下用同一幅图片做L1loss 不太合理。不过我感觉可以把 condEmbedding sampling之前的mean和ground truth做一个l1 loss. 

> 谢谢你的这篇论文，让我收益良多。只是有二个地方有些疑问，希望作者能给出你的看法：
> （1）为什么你不是直接将text_embedding送入网络中直接进行计算，而是对text_embedding进行了两种变化：condEmbedding 和 z。有了这两种变化相当于引入随机噪声，改变了文本数据的分布，感觉不是很合理啊。
> （2）实验过程中，你有尝试使用Image-image的L1损失么？
> 谢谢啦。
