### ISSUE TITLE
go wrong when using visdom to plot loss

### ISSUE THREAD

**Issue by yayeoCddy** [ypxie/HDGan#3]
some mistakes is 
![image](https://user-images.githubusercontent.com/16780698/41951241-6968f38e-79fc-11e8-8498-019e1036ba9f.png)
it may have errors in 
res = self.handler.line(
            X=steps,
            Y=values,
            win=self.name,
            update='append',
            opts=dict(title=self.name, legend=None),
            env=self.env
        )
so what i should do?

**Comment by ypxie** [comment]
1. don't set the flush rate as 1, 
2. did you check to make sure that the loss value (should be a scalar) is not nan?

**Comment by yayeoCddy** [comment]
1、i have checked the flush rate(args.display_freq) is 200 not 1
2、yeah i have checked the loss value by printing it and the result like this
![default](https://user-images.githubusercontent.com/16780698/41957378-5370d430-7a19-11e8-9da7-903f013345d4.JPG)
AND It should be noted that it dose not go wrong at the beginning but during the printing [epoch 1/600 iter 150/885] process

**Comment by yayeoCddy** [comment]
i modified the plot function like this, and the problem is solved
![image](https://user-images.githubusercontent.com/16780698/42508414-f8269a4e-847a-11e8-9a21-5a9d51131d0f.png)

**Comment by zizhaozhang** [comment]
@yayeoCddy  Thanks for providing the solution. It is due to the Visdom version issue. We have fixed it.

**Comment by huzaifasabir** [comment]
@zizhaozhang which  Visdom version are you using ?

**Comment by zizhaozhang** [comment]
@huzaifasabir  I tested on the latest version (0.1.8.4)
